---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jfrog-anyuid
  namespace: jfrog-helm
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jfrog-anyuid-scc
  namespace: jfrog-helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
subjects:
- kind: ServiceAccount
  name: jfrog-anyuid
  namespace: jfrog-helm